#!/bin/python3

#PUTS TEXT IN IMAGE
def put(image, msg):
    b = bytes(msg.encode())
    with open(image, 'ab') as f:

        f.write(b)

put("drako.jpg", 'how it go')

#EXTRACT TEXT FROM IMAGE
def extract(image):
    with open(image, 'rb') as f:
        content = f.read()
        offset = content.index(bytes.fromhex("FFD9"))

        f.seek(offset + 2)
        print(f.read())

extract("drako.jpg")
